# Generated by Django 5.0.6 on 2024-07-03 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_pogruz', models.CharField(max_length=1024)),
                ('city_vygruz', models.CharField(max_length=1024)),
                ('time_way', models.DateField(verbose_name=datetime.datetime(2024, 7, 3, 14, 48, 22, 289441))),
            ],
        ),
    ]
