# Generated by Django 5.1.3 on 2024-11-09 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_pogruz', models.CharField(max_length=1024)),
                ('city_vygruz', models.CharField(max_length=1024)),
                ('time_way', models.DateField(verbose_name=datetime.datetime(2024, 11, 9, 13, 26, 35, 915600))),
            ],
        ),
        migrations.CreateModel(
            name='Zapros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
